CREATE TABLE inventory_message_board_posts (
  id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  category VARCHAR(32) NOT NULL,
  process_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  handling_note VARCHAR(2000) NULL,
  author_id VARCHAR(80) NOT NULL,
  author_username VARCHAR(80) NOT NULL,
  author_name VARCHAR(80) NOT NULL,
  department_key VARCHAR(80) NOT NULL,
  department_name VARCHAR(80) NOT NULL,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  hidden BOOLEAN NOT NULL DEFAULT FALSE,
  withdrawn BOOLEAN NOT NULL DEFAULT FALSE,
  withdrawn_at DATETIME(6) NULL,
  hidden_at DATETIME(6) NULL,
  hidden_by VARCHAR(80) NULL,
  last_activity_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY idx_inventory_board_posts_order (pinned, last_activity_at),
  KEY idx_inventory_board_posts_filter (category, process_status, department_key),
  KEY idx_inventory_board_posts_author (author_id, created_at),
  KEY idx_inventory_board_posts_visibility (hidden, withdrawn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE inventory_message_board_replies (
  id VARCHAR(64) PRIMARY KEY,
  post_id VARCHAR(64) NOT NULL,
  content VARCHAR(2000) NOT NULL,
  author_id VARCHAR(80) NOT NULL,
  author_username VARCHAR(80) NOT NULL,
  author_name VARCHAR(80) NOT NULL,
  department_key VARCHAR(80) NOT NULL,
  department_name VARCHAR(80) NOT NULL,
  hidden BOOLEAN NOT NULL DEFAULT FALSE,
  withdrawn BOOLEAN NOT NULL DEFAULT FALSE,
  withdrawn_at DATETIME(6) NULL,
  hidden_at DATETIME(6) NULL,
  hidden_by VARCHAR(80) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  KEY idx_inventory_board_replies_post (post_id, created_at),
  KEY idx_inventory_board_replies_author (author_id, created_at),
  KEY idx_inventory_board_replies_visibility (hidden, withdrawn),
  CONSTRAINT fk_inventory_board_replies_post FOREIGN KEY (post_id) REFERENCES inventory_message_board_posts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE inventory_message_board_audit_logs (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  target_type VARCHAR(20) NOT NULL,
  target_id VARCHAR(64) NOT NULL,
  action VARCHAR(40) NOT NULL,
  operator_id VARCHAR(80) NOT NULL,
  operator_username VARCHAR(80) NOT NULL,
  operator_name VARCHAR(80) NOT NULL,
  department_key VARCHAR(80) NOT NULL,
  department_name VARCHAR(80) NOT NULL,
  detail_json TEXT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  KEY idx_inventory_board_audit_target (target_type, target_id, created_at),
  KEY idx_inventory_board_audit_operator (operator_id, created_at),
  KEY idx_inventory_board_audit_action (action, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
