CREATE TABLE inventory_quota_versions (
  id VARCHAR(64) PRIMARY KEY,
  version_code VARCHAR(64) NOT NULL,
  effective_date DATE NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  created_by VARCHAR(120) NOT NULL,
  confirmed_by VARCHAR(120) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_inventory_quota_version_code (version_code),
  UNIQUE KEY uk_inventory_quota_effective_date (effective_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE inventory_quota_rules (
  id VARCHAR(96) PRIMARY KEY,
  version_id VARCHAR(64) NOT NULL,
  department_key VARCHAR(64) NOT NULL,
  department_name VARCHAR(120) NOT NULL,
  source_row INT NOT NULL,
  service_group VARCHAR(160) NOT NULL,
  care_type VARCHAR(24) NOT NULL,
  material_name VARCHAR(255) NOT NULL,
  unit VARCHAR(64) NOT NULL,
  standard_quantity DECIMAL(18,6) NULL,
  fixed_adjustment DECIMAL(18,6) NOT NULL DEFAULT 0,
  measurement_scope VARCHAR(24) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_inventory_quota_rule_version FOREIGN KEY (version_id) REFERENCES inventory_quota_versions(id),
  UNIQUE KEY uk_inventory_quota_rule_source (version_id, department_key, source_row),
  INDEX idx_inventory_quota_rule_department (version_id, department_key, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE inventory_special_material_rules (
  id VARCHAR(64) PRIMARY KEY,
  department_key VARCHAR(64) NOT NULL,
  material_name VARCHAR(255) NOT NULL,
  unit VARCHAR(64) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  admin_note VARCHAR(1000) NOT NULL DEFAULT '',
  updated_by VARCHAR(120) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_inventory_special_material (department_key, material_name, unit),
  INDEX idx_inventory_special_material_department (department_key, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE inventory_quota_review_records (
  id VARCHAR(64) PRIMARY KEY,
  business_date DATE NOT NULL,
  department_key VARCHAR(64) NOT NULL,
  line_key VARCHAR(128) NOT NULL,
  material_name VARCHAR(255) NOT NULL,
  unit VARCHAR(64) NOT NULL,
  review_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  review_note VARCHAR(2000) NOT NULL DEFAULT '',
  reviewer_username VARCHAR(120) NOT NULL,
  reviewer_name VARCHAR(120) NOT NULL,
  reviewed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_inventory_quota_review_target (business_date, department_key, line_key),
  INDEX idx_inventory_quota_review_date (business_date, department_key, review_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO inventory_quota_versions (id, version_code, effective_date, status, created_by, confirmed_by)
VALUES ('quota-v1', 'quota-v1', CURRENT_DATE, 'ACTIVE', 'system-v32', 'system-v32');
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-4', 'quota-v1', 'physiotherapy', '理疗室', 4, '门诊患者', 'outpatient', 'pvc手套（双）', '双', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-5', 'quota-v1', 'physiotherapy', '理疗室', 5, '门诊患者', 'outpatient', '卫生纸（节）', '节', 4, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-6', 'quota-v1', 'physiotherapy', '理疗室', 6, '门诊患者', 'outpatient', '换药棉花敷料（个）', '个', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-7', 'quota-v1', 'physiotherapy', '理疗室', 7, '门诊患者', 'outpatient', '导尿灌肠管（个）', '个', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-8', 'quota-v1', 'physiotherapy', '理疗室', 8, '门诊患者', 'outpatient', '医用胶带（条）', '条', 3, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-9', 'quota-v1', 'physiotherapy', '理疗室', 9, '门诊患者', 'outpatient', '换药棉球（个）', '个', 4, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-10', 'quota-v1', 'physiotherapy', '理疗室', 10, '门诊患者', 'outpatient', '碘伏（ml）', 'ml', 5, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-11', 'quota-v1', 'physiotherapy', '理疗室', 11, '门诊患者', 'outpatient', '酒精消毒（ml）', 'ml', 5, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-12', 'quota-v1', 'physiotherapy', '理疗室', 12, '住院患者', 'inpatient', '换药碘伏棉球（个）', '个', 4, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-13', 'quota-v1', 'physiotherapy', '理疗室', 13, '住院患者', 'inpatient', '中单（张/天）', '张/天', 0.333, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-14', 'quota-v1', 'physiotherapy', '理疗室', 14, '住院患者', 'inpatient', '医用胶布（条）', '条', 3, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-15', 'quota-v1', 'physiotherapy', '理疗室', 15, '住院患者', 'inpatient', '换药卫生纸（张）', '张', 4, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-16', 'quota-v1', 'physiotherapy', '理疗室', 16, '住院患者', 'inpatient', '导尿管（灌肠管）（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-17', 'quota-v1', 'physiotherapy', '理疗室', 17, '住院患者', 'inpatient', '一次性白色隔离垫（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-18', 'quota-v1', 'physiotherapy', '理疗室', 18, '住院患者', 'inpatient', '换药棉花敷料（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-19', 'quota-v1', 'physiotherapy', '理疗室', 19, '住院患者', 'inpatient', '一次性马桶隔离膜（m）', 'm', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-20', 'quota-v1', 'physiotherapy', '理疗室', 20, '住院患者', 'inpatient', '艾条（个）', '个', 0.5, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-21', 'quota-v1', 'physiotherapy', '理疗室', 21, '住院患者', 'inpatient', 'pvc手套（双）', '双', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-22', 'quota-v1', 'physiotherapy', '理疗室', 22, '住院患者', 'inpatient', '红霉素（g）', 'g', 3, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-23', 'quota-v1', 'physiotherapy', '理疗室', 23, '住院患者', 'inpatient', '75%消毒酒精（ml）', 'ml', 5, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-24', 'quota-v1', 'physiotherapy', '理疗室', 24, '住院患者', 'inpatient', '碘伏消毒液（ml）', 'ml', 5, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-25', 'quota-v1', 'physiotherapy', '理疗室', 25, '住院患者', 'inpatient', '蓝色小铺巾（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-26', 'quota-v1', 'physiotherapy', '理疗室', 26, '住院患者', 'inpatient', '白色脱脂纱布块', '', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-27', 'quota-v1', 'physiotherapy', '理疗室', 27, '住院患者', 'inpatient', '橡胶检查手套（双）', '双', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-28', 'quota-v1', 'physiotherapy', '理疗室', 28, '住院患者', 'inpatient', '黑色垃圾袋（个/天）', '个/天', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-29', 'quota-v1', 'physiotherapy', '理疗室', 29, '住院患者', 'inpatient', '医疗垃圾袋（个/天）', '个/天', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-physiotherapy-30', 'quota-v1', 'physiotherapy', '理疗室', 30, '住院患者', 'inpatient', '口罩（个/天）', '个/天', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-4', 'quota-v1', 'laboratory', '检验科', 4, '门诊患者', 'outpatient', '紫头管（EDTA抗凝管）（支）', '支', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-5', 'quota-v1', 'laboratory', '检验科', 5, '门诊患者', 'outpatient', '蓝头管（枸橼酸钠抗凝管）（支）', '支', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-6', 'quota-v1', 'laboratory', '检验科', 6, '门诊患者', 'outpatient', '采血针（支）', '支', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-7', 'quota-v1', 'laboratory', '检验科', 7, '门诊患者', 'outpatient', '碘伏（ml）', 'ml', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-8', 'quota-v1', 'laboratory', '检验科', 8, '门诊患者', 'outpatient', '棉签（根）', '根', 3, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-9', 'quota-v1', 'laboratory', '检验科', 9, '门诊患者', 'outpatient', '止血带（根）', '根', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-10', 'quota-v1', 'laboratory', '检验科', 10, '门诊患者', 'outpatient', '凝血四项试剂（人份）', '人份', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-11', 'quota-v1', 'laboratory', '检验科', 11, '门诊患者', 'outpatient', '术前八项试剂（人份）', '人份', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-12', 'quota-v1', 'laboratory', '检验科', 12, '门诊患者', 'outpatient', '血常规试剂（人份）', '人份', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-13', 'quota-v1', 'laboratory', '检验科', 13, '门诊患者', 'outpatient', '血糖试纸（人份）', '人份', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-14', 'quota-v1', 'laboratory', '检验科', 14, '门诊患者', 'outpatient', 'A5纸（张）', '张', 4, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-15', 'quota-v1', 'laboratory', '检验科', 15, '门诊患者', 'outpatient', '心电图纸（张）', '张', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-16', 'quota-v1', 'laboratory', '检验科', 16, '门诊患者', 'outpatient', '棉球（个）', '个', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-17', 'quota-v1', 'laboratory', '检验科', 17, '住院患者', 'inpatient', '紫头管（EDTA抗凝管）（支）', '支', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-18', 'quota-v1', 'laboratory', '检验科', 18, '住院患者', 'inpatient', '蓝头管（枸橼酸钠抗凝管）（支）', '支', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-19', 'quota-v1', 'laboratory', '检验科', 19, '住院患者', 'inpatient', '绿头管（肝素钠抗凝管）（支）', '支', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-20', 'quota-v1', 'laboratory', '检验科', 20, '住院患者', 'inpatient', '采血针（支）', '支', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-21', 'quota-v1', 'laboratory', '检验科', 21, '住院患者', 'inpatient', '碘伏（ml）', 'ml', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-22', 'quota-v1', 'laboratory', '检验科', 22, '住院患者', 'inpatient', '棉签（根）', '根', 3, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-23', 'quota-v1', 'laboratory', '检验科', 23, '住院患者', 'inpatient', '止血带（根）', '根', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-24', 'quota-v1', 'laboratory', '检验科', 24, '住院患者', 'inpatient', '凝血四项试剂（人份）', '人份', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-25', 'quota-v1', 'laboratory', '检验科', 25, '住院患者', 'inpatient', '术前八项试剂（人份）', '人份', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-26', 'quota-v1', 'laboratory', '检验科', 26, '住院患者', 'inpatient', '血常规试剂（人份）', '人份', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-27', 'quota-v1', 'laboratory', '检验科', 27, '住院患者', 'inpatient', '生化试剂（人份）', '人份', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-28', 'quota-v1', 'laboratory', '检验科', 28, '住院患者', 'inpatient', '电解质试剂（人份）', '人份', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-29', 'quota-v1', 'laboratory', '检验科', 29, '住院患者', 'inpatient', '尿试纸条（支）', '支', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-30', 'quota-v1', 'laboratory', '检验科', 30, '住院患者', 'inpatient', '尿杯（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-31', 'quota-v1', 'laboratory', '检验科', 31, '住院患者', 'inpatient', 'A5纸（张）', '张', 6, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-32', 'quota-v1', 'laboratory', '检验科', 32, '住院患者', 'inpatient', '心电图纸（张）', '张', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-33', 'quota-v1', 'laboratory', '检验科', 33, '住院患者', 'inpatient', '棉球（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-34', 'quota-v1', 'laboratory', '检验科', 34, '其他耗材', 'other', 'PVC手套（双/人/天）', '双/人/天', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-35', 'quota-v1', 'laboratory', '检验科', 35, '其他耗材', 'other', '口罩（个/人/天）', '个/人/天', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-36', 'quota-v1', 'laboratory', '检验科', 36, '其他耗材', 'other', 'A4纸（张）', '张', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-37', 'quota-v1', 'laboratory', '检验科', 37, '其他耗材', 'other', '医疗垃圾袋（个/天）', '个/天', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-38', 'quota-v1', 'laboratory', '检验科', 38, '其他耗材', 'other', '利器盒', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-39', 'quota-v1', 'laboratory', '检验科', 39, '其他耗材', 'other', '小中单（个/天）', '个/天', 0.5, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-40', 'quota-v1', 'laboratory', '检验科', 40, '其他耗材', 'other', '大中单（个/天）', '个/天', 0.143, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-41', 'quota-v1', 'laboratory', '检验科', 41, '其他耗材', 'other', '卫生纸', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-42', 'quota-v1', 'laboratory', '检验科', 42, '其他耗材', 'other', '医用抗菌洗手液', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-43', 'quota-v1', 'laboratory', '检验科', 43, '其他耗材', 'other', '84消毒液', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-44', 'quota-v1', 'laboratory', '检验科', 44, '其他耗材', 'other', '一次性消毒凝胶', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-45', 'quota-v1', 'laboratory', '检验科', 45, '其他耗材', 'other', '生化DC-80清洗液', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-46', 'quota-v1', 'laboratory', '检验科', 46, '其他耗材', 'other', '血常规稀释液（ml）', 'ml', 20000, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-47', 'quota-v1', 'laboratory', '检验科', 47, '其他耗材', 'other', '溶血剂（ml）', 'ml', 600, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-48', 'quota-v1', 'laboratory', '检验科', 48, '其他耗材', 'other', '探头清洁液（ml）', 'ml', 50, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-49', 'quota-v1', 'laboratory', '检验科', 49, '其他耗材', 'other', '生化试剂14项', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-50', 'quota-v1', 'laboratory', '检验科', 50, '其他耗材', 'other', '电解质试剂', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-51', 'quota-v1', 'laboratory', '检验科', 51, '其他耗材', 'other', 'C14试剂', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-52', 'quota-v1', 'laboratory', '检验科', 52, '其他耗材', 'other', 'CRP试剂', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-laboratory-53', 'quota-v1', 'laboratory', '检验科', 53, '其他耗材', 'other', '糖化血红蛋白试剂', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-4', 'quota-v1', 'nursing', '护理部', 4, '门诊患者', 'outpatient', '止血带（条）', '条', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-5', 'quota-v1', 'nursing', '护理部', 5, '门诊患者', 'outpatient', '输液贴（片）', '片', 2, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-6', 'quota-v1', 'nursing', '护理部', 6, '门诊患者', 'outpatient', '20ml注射器', '', NULL, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-7', 'quota-v1', 'nursing', '护理部', 7, '住院患者', 'inpatient', '输液贴（片）', '片', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-8', 'quota-v1', 'nursing', '护理部', 8, '住院患者', 'inpatient', '止血带（人份）', '人份', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-9', 'quota-v1', 'nursing', '护理部', 9, '住院患者', 'inpatient', '20ml注射器（个/天）', '个/天', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-10', 'quota-v1', 'nursing', '护理部', 10, '住院患者', 'inpatient', '碘伏（ml）', 'ml', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-11', 'quota-v1', 'nursing', '护理部', 11, '住院患者', 'inpatient', '医疗废物垃圾袋（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-12', 'quota-v1', 'nursing', '护理部', 12, '住院患者', 'inpatient', '利器盒', '', NULL, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-13', 'quota-v1', 'nursing', '护理部', 13, '住院患者', 'inpatient', '84消毒', '', NULL, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-14', 'quota-v1', 'nursing', '护理部', 14, '住院患者', 'inpatient', 'A4纸（张/天）', '张/天', 20, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-15', 'quota-v1', 'nursing', '护理部', 15, '住院患者', 'inpatient', '医疗扎带（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-16', 'quota-v1', 'nursing', '护理部', 16, '住院患者', 'inpatient', '口罩（个/天）', '个/天', 3, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-17', 'quota-v1', 'nursing', '护理部', 17, '住院患者', 'inpatient', '棉签（根）', '根', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-18', 'quota-v1', 'nursing', '护理部', 18, '住院患者', 'inpatient', '黑色垃圾袋（个/天）', '个/天', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-19', 'quota-v1', 'nursing', '护理部', 19, '住院患者', 'inpatient', 'PVC手套（双/天）', '双/天', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-20', 'quota-v1', 'nursing', '护理部', 20, '住院患者', 'inpatient', '薄膜手套（双/天）', '双/天', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-21', 'quota-v1', 'nursing', '护理部', 21, '住院患者', 'inpatient', '50ml注射器（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-22', 'quota-v1', 'nursing', '护理部', 22, '住院患者', 'inpatient', '腕带（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-23', 'quota-v1', 'nursing', '护理部', 23, '住院患者', 'inpatient', '长尾夹（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-24', 'quota-v1', 'nursing', '护理部', 24, '住院患者', 'inpatient', '床头卡（个）', '个', 1, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-nursing-25', 'quota-v1', 'nursing', '护理部', 25, '住院患者', 'inpatient', '固体胶', '', NULL, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-4', 'quota-v1', 'tcm', '中医科', 4, '门诊中医套餐', 'outpatient', '手写处方（张）', '张', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-5', 'quota-v1', 'tcm', '中医科', 5, '门诊中医套餐', 'outpatient', '机打处方（张）', '张', 2, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-6', 'quota-v1', 'tcm', '中医科', 6, '门诊中医套餐', 'outpatient', '签字笔芯', '', NULL, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-7', 'quota-v1', 'tcm', '中医科', 7, '门诊中西医结合套餐', 'outpatient', '手写处方（张）', '张', 1, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-8', 'quota-v1', 'tcm', '中医科', 8, '门诊中西医结合套餐', 'outpatient', '机打处方（张）', '张', 3, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-9', 'quota-v1', 'tcm', '中医科', 9, '门诊中西医结合套餐', 'outpatient', '签字笔芯', '', NULL, 0, 'OUTPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-10', 'quota-v1', 'tcm', '中医科', 10, '住院中医套餐', 'inpatient', '手写处方（张）', '张', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-11', 'quota-v1', 'tcm', '中医科', 11, '住院中医套餐', 'inpatient', '签字笔芯', '', NULL, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-12', 'quota-v1', 'tcm', '中医科', 12, '住院中西医结合套餐', 'inpatient', '手写处方（张）', '张', 2, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-13', 'quota-v1', 'tcm', '中医科', 13, '住院中西医结合套餐', 'inpatient', '签字笔芯', '', NULL, 0, 'INPATIENT', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-4', 'quota-v1', 'operating', '手术室', 4, '有创面手术', 'other', '碘伏棉球（个）', '个', 20, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-5', 'quota-v1', 'operating', '手术室', 5, '有创面手术', 'other', '纱布块（包）', '包', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-6', 'quota-v1', 'operating', '手术室', 6, '有创面手术', 'other', '卫生纸（节）', '节', 20, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-7', 'quota-v1', 'operating', '手术室', 7, '有创面手术', 'other', '小中单（个）', '个', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-8', 'quota-v1', 'operating', '手术室', 8, '有创面手术', 'other', '大中单（个/天）', '个/天', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-9', 'quota-v1', 'operating', '手术室', 9, '有创面手术', 'other', '75%酒精（ml）', 'ml', 30, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-10', 'quota-v1', 'operating', '手术室', 10, '有创面手术', 'other', '20毫升注射器（个）', '个', 4, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-11', 'quota-v1', 'operating', '手术室', 11, '有创面手术', 'other', '5毫升蓝头注射器（个）', '个', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-12', 'quota-v1', 'operating', '手术室', 12, '有创面手术', 'other', '5毫升黄头注射器（个）', '个', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-13', 'quota-v1', 'operating', '手术室', 13, '有创面手术', 'other', '碘伏（ml）', 'ml', 70, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-14', 'quota-v1', 'operating', '手术室', 14, '有创面手术', 'other', '新洁尔棉球（粒）', '粒', 5, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-15', 'quota-v1', 'operating', '手术室', 15, '有创面手术', 'other', '医用胶带（m）', 'm', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-16', 'quota-v1', 'operating', '手术室', 16, '有创面手术', 'other', '透明胶带（m）', 'm', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-17', 'quota-v1', 'operating', '手术室', 17, '有创面手术', 'other', '黑线（m）', 'm', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-18', 'quota-v1', 'operating', '手术室', 18, '有创面手术', 'other', '圆针（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-19', 'quota-v1', 'operating', '手术室', 19, '有创面手术', 'other', 'PVC手套（只）', '只', 6, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-20', 'quota-v1', 'operating', '手术室', 20, '有创面手术', 'other', '橡胶手套（只）', '只', 4, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-21', 'quota-v1', 'operating', '手术室', 21, '有创面手术', 'other', '口罩（个）', '个', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-22', 'quota-v1', 'operating', '手术室', 22, '有创面手术', 'other', 'A4纸（张）', '张', 40, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-23', 'quota-v1', 'operating', '手术室', 23, '有创面手术', 'other', '10毫升过氧化氢', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-24', 'quota-v1', 'operating', '手术室', 24, '有创面手术', 'other', '刀片（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-25', 'quota-v1', 'operating', '手术室', 25, '有创面手术', 'other', '20厘米橡胶管', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-26', 'quota-v1', 'operating', '手术室', 26, '有创面手术', 'other', '手术衣（件）', '件', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-27', 'quota-v1', 'operating', '手术室', 27, '有创面手术', 'other', '帽子（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-28', 'quota-v1', 'operating', '手术室', 28, '有创面手术', 'other', '黑色垃圾袋（个）', '个', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-29', 'quota-v1', 'operating', '手术室', 29, '有创面手术', 'other', '黄色垃圾袋（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-30', 'quota-v1', 'operating', '手术室', 30, '有创面手术', 'other', '利器盒（个/天）', '个/天', 0.071, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-31', 'quota-v1', 'operating', '手术室', 31, '无创面手术', 'other', '碘伏棉球（粒）', '粒', 10, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-32', 'quota-v1', 'operating', '手术室', 32, '无创面手术', 'other', '纱布块（包）', '包', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-33', 'quota-v1', 'operating', '手术室', 33, '无创面手术', 'other', '卫生纸（节）', '节', 15, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-34', 'quota-v1', 'operating', '手术室', 34, '无创面手术', 'other', '小中单（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-35', 'quota-v1', 'operating', '手术室', 35, '无创面手术', 'other', '大中单（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-36', 'quota-v1', 'operating', '手术室', 36, '无创面手术', 'other', '75%酒精（ml）', 'ml', 20, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-37', 'quota-v1', 'operating', '手术室', 37, '无创面手术', 'other', '20毫升注射器（个）', '个', 4, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-38', 'quota-v1', 'operating', '手术室', 38, '无创面手术', 'other', '5毫升蓝头注射器（个）', '个', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-39', 'quota-v1', 'operating', '手术室', 39, '无创面手术', 'other', '5毫升黄头注射器（个）', '个', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-40', 'quota-v1', 'operating', '手术室', 40, '无创面手术', 'other', '碘伏（ml）', 'ml', 30, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-41', 'quota-v1', 'operating', '手术室', 41, '无创面手术', 'other', '新洁尔棉（粒）', '粒', 5, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-42', 'quota-v1', 'operating', '手术室', 42, '无创面手术', 'other', '医用胶带（m）', 'm', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-43', 'quota-v1', 'operating', '手术室', 43, '无创面手术', 'other', '透明胶带（m）', 'm', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-44', 'quota-v1', 'operating', '手术室', 44, '无创面手术', 'other', 'PVC手套（只）', '只', 6, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-45', 'quota-v1', 'operating', '手术室', 45, '无创面手术', 'other', '橡胶手套（只）', '只', 4, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-46', 'quota-v1', 'operating', '手术室', 46, '无创面手术', 'other', '口罩（个/天）', '个/天', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-47', 'quota-v1', 'operating', '手术室', 47, '无创面手术', 'other', 'A4纸（张）', '张', 15, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-48', 'quota-v1', 'operating', '手术室', 48, '无创面手术', 'other', '手术衣（件）', '件', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-49', 'quota-v1', 'operating', '手术室', 49, '无创面手术', 'other', '帽子（个/天）', '个/天', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-50', 'quota-v1', 'operating', '手术室', 50, '无创面手术', 'other', '黑色垃圾袋（个/天）', '个/天', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-51', 'quota-v1', 'operating', '手术室', 51, '无创面手术', 'other', '黄色垃圾袋（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-operating-52', 'quota-v1', 'operating', '手术室', 52, '无创面手术', 'other', '利器盒（个/天）', '个/天', 0.071, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-4', 'quota-v1', 'anesthesia', '麻醉室', 4, '麻醉室', 'other', '输液器（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-5', 'quota-v1', 'anesthesia', '麻醉室', 5, '麻醉室', 'other', '20毫升耦合剂（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-6', 'quota-v1', 'anesthesia', '麻醉室', 6, '麻醉室', 'other', '75%酒精（ml）', 'ml', 30, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-7', 'quota-v1', 'anesthesia', '麻醉室', 7, '麻醉室', 'other', '棉签（个）', '个', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-8', 'quota-v1', 'anesthesia', '麻醉室', 8, '麻醉室', 'other', '碘伏（ml）', 'ml', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-9', 'quota-v1', 'anesthesia', '麻醉室', 9, '麻醉室', 'other', '止血带（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-10', 'quota-v1', 'anesthesia', '麻醉室', 10, '麻醉室', 'other', '卫生纸（节）', '节', 20, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-11', 'quota-v1', 'anesthesia', '麻醉室', 11, '麻醉室', 'other', '84消毒液（ml/天）', 'ml/天', 40, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-12', 'quota-v1', 'anesthesia', '麻醉室', 12, '麻醉室', 'other', '95%酒精（ml）', 'ml', 30, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-13', 'quota-v1', 'anesthesia', '麻醉室', 13, '麻醉室', 'other', '黄色垃圾袋（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-14', 'quota-v1', 'anesthesia', '麻醉室', 14, '麻醉室', 'other', '大中单（个/天）', '个/天', 0.333, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-15', 'quota-v1', 'anesthesia', '麻醉室', 15, '麻醉室', 'other', '小中单（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-16', 'quota-v1', 'anesthesia', '麻醉室', 16, '麻醉室', 'other', '手术衣（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-17', 'quota-v1', 'anesthesia', '麻醉室', 17, '麻醉室', 'other', '20毫升注射器（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-18', 'quota-v1', 'anesthesia', '麻醉室', 18, '麻醉室', 'other', '酶液（ml/天）', 'ml/天', 80, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-19', 'quota-v1', 'anesthesia', '麻醉室', 19, '麻醉室', 'other', '戊二醛（瓶/天）', '瓶/天', 0.429, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-20', 'quota-v1', 'anesthesia', '麻醉室', 20, '麻醉室', 'other', '纱布块', '', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-21', 'quota-v1', 'anesthesia', '麻醉室', 21, '麻醉室', 'other', '口罩（个/天）', '个/天', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-22', 'quota-v1', 'anesthesia', '麻醉室', 22, '麻醉室', 'other', '帽子（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-23', 'quota-v1', 'anesthesia', '麻醉室', 23, '麻醉室', 'other', 'PVC手套（只）', '只', 4, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-24', 'quota-v1', 'anesthesia', '麻醉室', 24, '麻醉室', 'other', '橡胶手套（只）', '只', 4, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-25', 'quota-v1', 'anesthesia', '麻醉室', 25, '麻醉室', 'other', 'A4纸（张）', '张', 5, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-26', 'quota-v1', 'anesthesia', '麻醉室', 26, '麻醉室', 'other', '鼻氧管（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-27', 'quota-v1', 'anesthesia', '麻醉室', 27, '麻醉室', 'other', '5毫升蓝色注射器（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-28', 'quota-v1', 'anesthesia', '麻醉室', 28, '麻醉室', 'other', '双面胶（cm）', 'cm', 5, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-anesthesia-29', 'quota-v1', 'anesthesia', '麻醉室', 29, '麻醉室', 'other', '咬口器（胃镜）（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-4', 'quota-v1', 'endoscopy', '胃肠镜', 4, '胃肠镜', 'other', '输液器（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-5', 'quota-v1', 'endoscopy', '胃肠镜', 5, '胃肠镜', 'other', '20毫升耦合剂（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-6', 'quota-v1', 'endoscopy', '胃肠镜', 6, '胃肠镜', 'other', '75%酒精（ml）', 'ml', 30, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-7', 'quota-v1', 'endoscopy', '胃肠镜', 7, '胃肠镜', 'other', '棉签（个）', '个', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-8', 'quota-v1', 'endoscopy', '胃肠镜', 8, '胃肠镜', 'other', '碘伏（ml）', 'ml', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-9', 'quota-v1', 'endoscopy', '胃肠镜', 9, '胃肠镜', 'other', '止血带（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-10', 'quota-v1', 'endoscopy', '胃肠镜', 10, '胃肠镜', 'other', '卫生纸（节）', '节', 20, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-11', 'quota-v1', 'endoscopy', '胃肠镜', 11, '胃肠镜', 'other', '84消毒液（ml/天）', 'ml/天', 40, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-12', 'quota-v1', 'endoscopy', '胃肠镜', 12, '胃肠镜', 'other', '95%酒精（ml）', 'ml', 30, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-13', 'quota-v1', 'endoscopy', '胃肠镜', 13, '胃肠镜', 'other', '黄色垃圾袋（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-14', 'quota-v1', 'endoscopy', '胃肠镜', 14, '胃肠镜', 'other', '大中单（个/天）', '个/天', 0.333, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-15', 'quota-v1', 'endoscopy', '胃肠镜', 15, '胃肠镜', 'other', '小中单（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-16', 'quota-v1', 'endoscopy', '胃肠镜', 16, '胃肠镜', 'other', '手术衣（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-17', 'quota-v1', 'endoscopy', '胃肠镜', 17, '胃肠镜', 'other', '20毫升注射器（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-18', 'quota-v1', 'endoscopy', '胃肠镜', 18, '胃肠镜', 'other', '酶液（ml/天）', 'ml/天', 80, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-19', 'quota-v1', 'endoscopy', '胃肠镜', 19, '胃肠镜', 'other', '戊二醛（瓶/天）', '瓶/天', 0.429, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-20', 'quota-v1', 'endoscopy', '胃肠镜', 20, '胃肠镜', 'other', '纱布块', '', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-21', 'quota-v1', 'endoscopy', '胃肠镜', 21, '胃肠镜', 'other', '口罩（个/天）', '个/天', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-22', 'quota-v1', 'endoscopy', '胃肠镜', 22, '胃肠镜', 'other', '帽子（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-23', 'quota-v1', 'endoscopy', '胃肠镜', 23, '胃肠镜', 'other', 'PVC手套（只）', '只', 4, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-24', 'quota-v1', 'endoscopy', '胃肠镜', 24, '胃肠镜', 'other', '橡胶手套（只）', '只', 4, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-25', 'quota-v1', 'endoscopy', '胃肠镜', 25, '胃肠镜', 'other', 'A4纸（张）', '张', 5, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-26', 'quota-v1', 'endoscopy', '胃肠镜', 26, '胃肠镜', 'other', '鼻氧管（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-27', 'quota-v1', 'endoscopy', '胃肠镜', 27, '胃肠镜', 'other', '5毫升蓝色注射器（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-28', 'quota-v1', 'endoscopy', '胃肠镜', 28, '胃肠镜', 'other', '双面胶（cm）', 'cm', 5, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-endoscopy-29', 'quota-v1', 'endoscopy', '胃肠镜', 29, '胃肠镜', 'other', '咬口器（胃镜）（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-4', 'quota-v1', 'inspection', '检查室', 4, '新病号/复查病患', 'other', '检查手套（支）', '支', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-5', 'quota-v1', 'inspection', '检查室', 5, '新病号/复查病患', 'other', '薄膜手套（副）', '副', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-6', 'quota-v1', 'inspection', '检查室', 6, '新病号/复查病患', 'other', '白色铺巾（张）', '张', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-7', 'quota-v1', 'inspection', '检查室', 7, '新病号/复查病患', 'other', '石蜡油（ml）', 'ml', 5, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-8', 'quota-v1', 'inspection', '检查室', 8, '新病号/复查病患', 'other', '卫生纸（节）', '节', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-9', 'quota-v1', 'inspection', '检查室', 9, '新病号/复查病患', 'other', '碘伏棉球（粒）', '粒', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-10', 'quota-v1', 'inspection', '检查室', 10, '新病号/复查病患', 'other', '棉纱布（块）', '块', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-11', 'quota-v1', 'inspection', '检查室', 11, '新病号/复查病患', 'other', '胶带（cm）', 'cm', 80, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-12', 'quota-v1', 'inspection', '检查室', 12, '每天固定使用', 'other', '医疗垃圾袋（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-13', 'quota-v1', 'inspection', '检查室', 13, '每天固定使用', 'other', '黑色垃圾袋（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-14', 'quota-v1', 'inspection', '检查室', 14, '每天固定使用', 'other', '84消毒液（ml）', 'ml', 10, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-15', 'quota-v1', 'inspection', '检查室', 15, '每天固定使用', 'other', '洗手液（ml）', 'ml', 10, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-16', 'quota-v1', 'inspection', '检查室', 16, '每天固定使用', 'other', '手消（ml）', 'ml', 10, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-17', 'quota-v1', 'inspection', '检查室', 17, '每天固定使用', 'other', '口罩（个/天）', '个/天', 2, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-18', 'quota-v1', 'inspection', '检查室', 18, '每天固定使用', 'other', '标签贴（个/天）', '个/天', 0.286, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-19', 'quota-v1', 'inspection', '检查室', 19, '每天固定使用', 'other', '处方签', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-inspection-20', 'quota-v1', 'inspection', '检查室', 20, '每天固定使用', 'other', '中单（个/天）', '个/天', 0.429, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-logistics-4', 'quota-v1', 'logistics', '后勤保洁', 4, '后勤保洁', 'other', '垃圾袋（个/天）', '个/天', 46, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-logistics-5', 'quota-v1', 'logistics', '后勤保洁', 5, '后勤保洁', 'other', '84消毒液（瓶/天）', '瓶/天', 0.133, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-logistics-6', 'quota-v1', 'logistics', '后勤保洁', 6, '后勤保洁', 'other', '洁厕灵（瓶/天）', '瓶/天', 0.067, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-logistics-7', 'quota-v1', 'logistics', '后勤保洁', 7, '后勤保洁', 'other', '口罩（个/天）', '个/天', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-logistics-8', 'quota-v1', 'logistics', '后勤保洁', 8, '后勤保洁', 'other', '拖把、扫把等', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-western-pharmacy-4', 'quota-v1', 'western-pharmacy', '西药房', 4, '西药房', 'other', '小透明袋子（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-western-pharmacy-5', 'quota-v1', 'western-pharmacy', '西药房', 5, '西药房', 'other', '打印纸', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-cashier-4', 'quota-v1', 'cashier', '收费室', 4, '收费室', 'other', 'A4纸（张）', '张', 8, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-cashier-5', 'quota-v1', 'cashier', '收费室', 5, '收费室', 'other', 'A4纸（张）', '张', 3, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-cashier-6', 'quota-v1', 'cashier', '收费室', 6, '收费室', 'other', '针式打印纸', '', NULL, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-pharmacy-4', 'quota-v1', 'tcm-pharmacy', '中药房', 4, '中药房', 'other', '小透明袋子（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-pharmacy-5', 'quota-v1', 'tcm-pharmacy', '中药房', 5, '中药房', 'other', '大袋子（个）', '个', 1, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-pharmacy-6', 'quota-v1', 'tcm-pharmacy', '中药房', 6, '中药房', 'other', 'Pvc手套（盒/天）', '盒/天', 0.033, 0, 'OTHER', 1);
INSERT INTO inventory_quota_rules (id, version_id, department_key, department_name, source_row, service_group, care_type, material_name, unit, standard_quantity, fixed_adjustment, measurement_scope, enabled) VALUES ('qv1-tcm-pharmacy-7', 'quota-v1', 'tcm-pharmacy', '中药房', 7, '中药房', 'other', '针式打印纸', '', NULL, 0, 'OTHER', 1);
