CREATE TABLE inventory_quota_audit_log (
  id VARCHAR(96) PRIMARY KEY,
  version_id VARCHAR(64) NOT NULL,
  version_code VARCHAR(64) NOT NULL,
  department_key VARCHAR(64) NOT NULL,
  department_name VARCHAR(120) NOT NULL,
  material_name VARCHAR(255) NOT NULL,
  unit VARCHAR(64) NOT NULL,
  service_group VARCHAR(160) NOT NULL,
  action VARCHAR(24) NOT NULL,
  before_standard_quantity DECIMAL(18,6) NULL,
  after_standard_quantity DECIMAL(18,6) NULL,
  before_fixed_adjustment DECIMAL(18,6) NULL,
  after_fixed_adjustment DECIMAL(18,6) NULL,
  before_enabled TINYINT(1) NULL,
  after_enabled TINYINT(1) NULL,
  before_measurement_scope VARCHAR(24) NULL,
  after_measurement_scope VARCHAR(24) NULL,
  operator_username VARCHAR(120) NOT NULL,
  operator_name VARCHAR(120) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_inventory_quota_audit_version (version_id, created_at),
  INDEX idx_inventory_quota_audit_department (department_key, created_at),
  INDEX idx_inventory_quota_audit_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
